### ISSUE TITLE
Understand client authentication with AWS

### ISSUE THREAD

**Issue by UpGado** [approzium/approzium#2]
This includes:
- figuring out what what to get from STS and what to send to Authenticator.

**Comment by timothydnguyen** [comment]
1. service connects to Amazon STS's [AssumeRole](https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html) using its stored Access Key ID, Secret Key, and the ARN of its requested role. It receives back temporary credentials. These credentials are used to sign a [GetCallerIdentity](https://docs.aws.amazon.com/STS/latest/APIReference/API_GetCallerIdentity.html) request, which then becomes the non-repudiable identity of the service.

2. service sends the challenge, and signed GetCallerIdentity request to the authenticator.

3. the authenticator executes the signed GetCallerIdentity request, which returns the ARN of the IAM role assigned to the service.
