### ISSUE TITLE
Add observability for caller identity

### ISSUE THREAD

**Issue by tyrannosaurus-becks** [approzium/approzium#39]
Need to capture metadata about the entity behind an authentication - stuff like instance ID, instance ARN, and more, specific fields TBD.

**Comment by tyrannosaurus-becks** [comment]
Do this via logging and having filebeat or whatever ship it off to the customer's stack, which would be configurable.

**Comment by tyrannosaurus-becks** [comment]
Also metrics in the OpenCensus format.

**Comment by tyrannosaurus-becks** [comment]
Add alerting capabilities (may be more of a later thing, separate ticket)

**Comment by tyrannosaurus-becks** [comment]
Probably simply adding a field for logged metadata, and including in it an entity ARN and instance ID would be the minimum data.

**Comment by timothydnguyen** [comment]
We understand the value of logging the caller identity information in the authenticator server, but what is the expected use case for using the information on the client end? The information is verified in the authenticator server, but not in the client.
